// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG7311_POE_Part2_ST10257863.Data;

#nullable disable

namespace PROG7311_POE_Part2_ST10257863.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513145423_MadeFarmNullableInProduct")]
    partial class MadeFarmNullableInProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "California, USA",
                            Name = "Oakridge Organic Farm"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Free State, South Africa",
                            Name = "Sunny Meadows Dairy"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Limpopo, South Africa",
                            Name = "Green Hills Citrus Estate"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Texas, USA",
                            Name = "Red Earth Livestock Farm"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Stellenbosch, South Africa",
                            Name = "Valley View Vineyard"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Mpumalanga, South Africa",
                            Name = "Cedar Ridge Poultry Farm"
                        },
                        new
                        {
                            Id = 7,
                            Location = "KwaZulu-Natal, South Africa",
                            Name = "Blue River Aquafarm"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Chilean Andes",
                            Name = "Mountain Edge Alpaca Farm"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Oregon, USA",
                            Name = "Riverbend Vegetable Farm"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Northern Cape, South Africa",
                            Name = "Karoo Honey & Herb Farm"
                        });
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Strawberries",
                            ProductionDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Blueberries",
                            ProductionDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Kale",
                            ProductionDate = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Spinach",
                            ProductionDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Lettuce",
                            ProductionDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Broccoli",
                            ProductionDate = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Carrots",
                            ProductionDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Tomatoes",
                            ProductionDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Cucumbers",
                            ProductionDate = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Zucchini",
                            ProductionDate = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Apples",
                            ProductionDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Pears",
                            ProductionDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Potatoes",
                            ProductionDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Onions",
                            ProductionDate = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Bell Peppers",
                            ProductionDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Corn",
                            ProductionDate = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Beets",
                            ProductionDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Radish",
                            ProductionDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Celery",
                            ProductionDate = new DateTime(2024, 8, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 20,
                            Category = "Organic Produce",
                            FarmId = 1,
                            Name = "Organic Cauliflower",
                            ProductionDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 21,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Fresh Whole Milk",
                            ProductionDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 22,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Skim Milk",
                            ProductionDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 23,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Yogurt",
                            ProductionDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 24,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Cheese",
                            ProductionDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 25,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Butter",
                            ProductionDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 26,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Cream",
                            ProductionDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 27,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Ice Cream",
                            ProductionDate = new DateTime(2024, 7, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 28,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Buttermilk",
                            ProductionDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 29,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Cottage Cheese",
                            ProductionDate = new DateTime(2024, 7, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 30,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Sour Cream",
                            ProductionDate = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 31,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Goat Milk",
                            ProductionDate = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 32,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Raw Milk",
                            ProductionDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 33,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Chocolate Milk",
                            ProductionDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 34,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Strawberry Milk",
                            ProductionDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 35,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Lactose-Free Milk",
                            ProductionDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 36,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Farm Eggs",
                            ProductionDate = new DateTime(2024, 7, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 37,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Free-range Chicken",
                            ProductionDate = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 38,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Chicken Sausages",
                            ProductionDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 39,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Beef Mince",
                            ProductionDate = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 40,
                            Category = "Dairy",
                            FarmId = 2,
                            Name = "Dairy Cattle Manure",
                            ProductionDate = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 41,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Oranges",
                            ProductionDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 42,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Naartjies",
                            ProductionDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 43,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Lemons",
                            ProductionDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 44,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Limes",
                            ProductionDate = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 45,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Grapefruits",
                            ProductionDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 46,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Clementines",
                            ProductionDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 47,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Blood Oranges",
                            ProductionDate = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 48,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Citrus Juice",
                            ProductionDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 49,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Citrus Marmalade",
                            ProductionDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 50,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Dried Orange Slices",
                            ProductionDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 51,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Orange Essential Oil",
                            ProductionDate = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 52,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Lemon Curd",
                            ProductionDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 53,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Citrus Zest Powder",
                            ProductionDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 54,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Lemonade Concentrate",
                            ProductionDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 55,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Citrus Pectin",
                            ProductionDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 56,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Candied Orange Peel",
                            ProductionDate = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 57,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Orange Soap",
                            ProductionDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 58,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Citrus Hand Sanitizer",
                            ProductionDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 59,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Citrus-flavored Honey",
                            ProductionDate = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 60,
                            Category = "Citrus",
                            FarmId = 3,
                            Name = "Lemon Vinegar",
                            ProductionDate = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 61,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Angus Beef",
                            ProductionDate = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 62,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Pork Chops",
                            ProductionDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 63,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Lamb Meat",
                            ProductionDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 64,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Goat Meat",
                            ProductionDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 65,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Chicken Meat",
                            ProductionDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 66,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Duck Meat",
                            ProductionDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 67,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Turkey Meat",
                            ProductionDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 68,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Eggs (Chicken)",
                            ProductionDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 69,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Duck Eggs",
                            ProductionDate = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 70,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Wool",
                            ProductionDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 71,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Cow Hides",
                            ProductionDate = new DateTime(2024, 7, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 72,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Leather",
                            ProductionDate = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 73,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Goat Milk",
                            ProductionDate = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 74,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Manure",
                            ProductionDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 75,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Honey (from beehives)",
                            ProductionDate = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 76,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Chicken Feet",
                            ProductionDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 77,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Bone Broth Packs",
                            ProductionDate = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 78,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Liver",
                            ProductionDate = new DateTime(2024, 8, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 79,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Pet Food",
                            ProductionDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 80,
                            Category = "Livestock",
                            FarmId = 4,
                            Name = "Feathers",
                            ProductionDate = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 81,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Cabernet Sauvignon",
                            ProductionDate = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 82,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Merlot",
                            ProductionDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 83,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Shiraz",
                            ProductionDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 84,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Pinotage",
                            ProductionDate = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 85,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Chardonnay",
                            ProductionDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 86,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Sauvignon Blanc",
                            ProductionDate = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 87,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Rosé",
                            ProductionDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 88,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Sparkling Wine",
                            ProductionDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 89,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Wine Vinegar",
                            ProductionDate = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 90,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Grape Juice",
                            ProductionDate = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 91,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Raisins",
                            ProductionDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 92,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Table Grapes",
                            ProductionDate = new DateTime(2024, 8, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 93,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Grape Jam",
                            ProductionDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 94,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Grape Seed Oil",
                            ProductionDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 95,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Grape Seed Flour",
                            ProductionDate = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 96,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Red Wine Sauce",
                            ProductionDate = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 97,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Mulled Wine Mix",
                            ProductionDate = new DateTime(2024, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 98,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Brandy",
                            ProductionDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 99,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Fortified Wine",
                            ProductionDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 100,
                            Category = "Wine",
                            FarmId = 5,
                            Name = "Wine-Infused Cheese",
                            ProductionDate = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 101,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Broilers",
                            ProductionDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 102,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Layer Hens",
                            ProductionDate = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 103,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Eggs",
                            ProductionDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 104,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Duck Eggs",
                            ProductionDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 105,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Quail Eggs",
                            ProductionDate = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 106,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Quail Meat",
                            ProductionDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 107,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Wings",
                            ProductionDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 108,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Breasts",
                            ProductionDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 109,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Livers",
                            ProductionDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 110,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Gizzards",
                            ProductionDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 111,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Feed",
                            ProductionDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 112,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Compost",
                            ProductionDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 113,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Organic Chicken Fertilizer",
                            ProductionDate = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 114,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Dressed Duck",
                            ProductionDate = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 115,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Smoked Chicken",
                            ProductionDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 116,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Sausages",
                            ProductionDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 117,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Burgers",
                            ProductionDate = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 118,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Chicken Nuggets",
                            ProductionDate = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 119,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Frozen Chicken",
                            ProductionDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 120,
                            Category = "Poultry",
                            FarmId = 6,
                            Name = "Feather Meal",
                            ProductionDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 121,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Tilapia",
                            ProductionDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 122,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Catfish",
                            ProductionDate = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 123,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Trout",
                            ProductionDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 124,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fresh Prawns",
                            ProductionDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 125,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Shrimp",
                            ProductionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 126,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Crayfish",
                            ProductionDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 127,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fish Fillets",
                            ProductionDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 128,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Smoked Fish",
                            ProductionDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 129,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Dried Fish",
                            ProductionDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 130,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fish Oil",
                            ProductionDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 131,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fish Meal",
                            ProductionDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 132,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fish Sauce",
                            ProductionDate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 133,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Aquarium Fish",
                            ProductionDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 134,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Ornamental Koi",
                            ProductionDate = new DateTime(2024, 7, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 135,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Freshwater Mussels",
                            ProductionDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 136,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Live Fish Feed",
                            ProductionDate = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 137,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Seaweed",
                            ProductionDate = new DateTime(2024, 7, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 138,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fish Roe",
                            ProductionDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 139,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Fish Fertilizer",
                            ProductionDate = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 140,
                            Category = "Aquaculture",
                            FarmId = 7,
                            Name = "Aquaponic Lettuce",
                            ProductionDate = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 141,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "White Alpaca Wool",
                            ProductionDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 142,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Black Alpaca Wool",
                            ProductionDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 143,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Brown Alpaca Wool",
                            ProductionDate = new DateTime(2024, 8, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 144,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Hand-Spun Yarn",
                            ProductionDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 145,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Blankets",
                            ProductionDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 146,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Scarves",
                            ProductionDate = new DateTime(2024, 9, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 147,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Socks",
                            ProductionDate = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 148,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Alpaca Rugs",
                            ProductionDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 149,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Alpaca Hats",
                            ProductionDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 150,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Felt Sheets",
                            ProductionDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 151,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Gloves",
                            ProductionDate = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 152,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Baby Alpaca Fiber",
                            ProductionDate = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 153,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Dyed Wool",
                            ProductionDate = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 154,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Stuffed Toys",
                            ProductionDate = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 155,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Alpaca Wool Sweaters",
                            ProductionDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 156,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Alpaca Manure",
                            ProductionDate = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 157,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Alpaca Breeding Stock",
                            ProductionDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 158,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Throws",
                            ProductionDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 159,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Vests",
                            ProductionDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 160,
                            Category = "Fiber",
                            FarmId = 8,
                            Name = "Wool Art Supplies",
                            ProductionDate = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 161,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Tomatoes",
                            ProductionDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 162,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Cucumbers",
                            ProductionDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 163,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Lettuce",
                            ProductionDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 164,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Carrots",
                            ProductionDate = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 165,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Cabbage",
                            ProductionDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 166,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Zucchini",
                            ProductionDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 167,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Green Beans",
                            ProductionDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 168,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Peas",
                            ProductionDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 169,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Corn",
                            ProductionDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 170,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Sweet Potatoes",
                            ProductionDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 171,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Spinach",
                            ProductionDate = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 172,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Bell Peppers",
                            ProductionDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 173,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Chili Peppers",
                            ProductionDate = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 174,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Butternut Squash",
                            ProductionDate = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 175,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Pumpkin",
                            ProductionDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 176,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Eggplant",
                            ProductionDate = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 177,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Artichokes",
                            ProductionDate = new DateTime(2024, 7, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 178,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Garlic",
                            ProductionDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 179,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Ginger",
                            ProductionDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 180,
                            Category = "Vegetables",
                            FarmId = 9,
                            Name = "Leeks",
                            ProductionDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 181,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Wildflower Honey",
                            ProductionDate = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 182,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Karoo Fynbos Honey",
                            ProductionDate = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 183,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Beeswax",
                            ProductionDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 184,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Propolis",
                            ProductionDate = new DateTime(2024, 8, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 185,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Royal Jelly",
                            ProductionDate = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 186,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Honeycomb",
                            ProductionDate = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 187,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Lavender",
                            ProductionDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 188,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Rosemary",
                            ProductionDate = new DateTime(2024, 6, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 189,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Thyme",
                            ProductionDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 190,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Oregano",
                            ProductionDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 191,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Mint",
                            ProductionDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 192,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Sage",
                            ProductionDate = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 193,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Basil",
                            ProductionDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 194,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Herbal Tea Mix",
                            ProductionDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 195,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Essential Oils",
                            ProductionDate = new DateTime(2024, 6, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 196,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Dried Herbs",
                            ProductionDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 197,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Herbal Soap",
                            ProductionDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 198,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Honey Lip Balm",
                            ProductionDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 199,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Beeswax Candles",
                            ProductionDate = new DateTime(2024, 7, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 200,
                            Category = "Herbs & Honey",
                            FarmId = 10,
                            Name = "Pollen Capsules",
                            ProductionDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Employee", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("PROG7311_POE_Part2_ST10257863.Data.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Farmer", b =>
                {
                    b.HasOne("PROG7311_POE_Part2_ST10257863.Data.Farm", "Farm")
                        .WithMany("Farmers")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithOne("FarmerProfile")
                        .HasForeignKey("PROG7311_POE_Part2_ST10257863.Data.Farmer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Products", b =>
                {
                    b.HasOne("PROG7311_POE_Part2_ST10257863.Data.Farm", "Farm")
                        .WithMany("Products")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("PROG7311_POE_Part2_ST10257863.Data.Farm", b =>
                {
                    b.Navigation("Farmers");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("CustomerProfile")
                        .IsRequired();

                    b.Navigation("EmployeeProfile")
                        .IsRequired();

                    b.Navigation("FarmerProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
